item {
    id: 1
    name: 'Ara Hall'
}

item {
    id: 2
    name: 'CWB'
}

item {
    id: 3
    name: 'College Of Education'
}

item {
    id: 4
    name: 'College of Commerce2'
}

item {
    id: 5
    name: 'College of Marine Science'
}

item {
    id: 6
    name: 'College of Medicine'
}

item {
    id: 7
    name: 'College of Natural Science'
}

item {
    id: 8
    name: 'College of Nursing'
}

item {
    id: 9
    name: 'College of Social Science'
}

item {
    id: 10
    name: 'College of Social Sciences'
}

item {
    id: 11
    name: 'Cultural lecture hall'
}

item {
    id: 12
    name: 'Digital Library'
}

item {
    id: 13
    name: 'Engineering College Building 4'
}

item {
    id: 14
    name: 'Foreign Language Institute'
}

item {
    id: 15
    name: 'Global House'
}

item {
    id: 16
    name: 'Gym'
}

item {
    id: 17
    name: 'Information Telecommunication Center'
}

item {
    id: 18
    name: 'Joint Experimental Labs '
}

item {
    id: 19
    name: 'KMG'
}

item {
    id: 20
    name: 'Main Building'
}

item {
    id: 21
    name: 'Main Building of University'
}

item {
    id: 22
    name: 'Main Gate'
}

item {
    id: 23
    name: 'Military Education Unit'
}

item {
    id: 24
    name: 'Museum'
}

item {
    id: 25
    name: 'Natural Science2 '
}

item {
    id: 26
    name: 'Second Library'
}

item {
    id: 27
    name: 'Security Office'
}

item {
    id: 28
    name: 'Student Hall'
}